export const GOOGLE_MAPS_API_KEY = "AIzaSyBpQ3JIiI4SqKfPyu9W408SnjF1-YGNmdE";

export const NAVIGATOR_SCREEN = {
  HOME: "HOME",
  MESSAGE: "MESSAGE",
  HOME_SCREEN: "HOME_SCREEN",
  HISTORY: "HISTORY",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  PROFILE: "PROFILE",
  BOOK_CAR: "BOOK_CAR",
  SEARCH_LOCATION: "SEARCH_LOCATION",
};

export const GENDER_ENUM = {
  MALE: { text: "Nam" },
  FEMALE: { text: "Nữ" },
  OTHER: { text: "Khác" },
};
